name: kooha_test
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  styled_widget: ^0.4.1
  google_fonts: ^6.0.0
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 500
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 300
